language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cd $TRAVIS_BUILD_DIR
  - cargo build
  - cargo test
  - cargo build --all-features
  - cargo test --all-features
after_success: |-
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cargo doc --all-features &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  sudo pip install ghp-import &&
  ghp-import -n target/doc &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  matrix:
    secure: f7UOcOtfHOAS6pWKRLOyeeEh/ZUC5P/ijMAvy0yMyaWB6yF9e58hM6GDSJnhK8op7iJReo1wnW6wHWkbl1Q8Eaz1jrPKQo1zKu24eFUcBUdeDt2HFvXzQi+zCq6DM5Z8ENm1xbbmpQTXtlmyuEDjv++07dtckkXH82YDIuLVs9R4+Kv/XqmmyrGtFSljHDS1XbeAqxfuo98bzm42vjkqwpYjbNVwGIn0P+F8na0bxCeWrh7PXEV9BZ/D1642H9aJ+jiRotn3flSyAycPyJ8CyZ2LRKVYYmoN+s5hGjb+2JQKy+x0LiDh0ohXDbfdIVxIDsqzHiWXEuh2IrpDLYBTXwmL3CZkskPl7GhEQL4VZj64DxnqVWhP3zcLA4kKA+XgGpsxPsGGYi3RtFZuzhu99fgwrU0OfyjvYgTEoBKRdGgLj/ywmXX8/+X4bDsCPjyry8eEJeMzwV7mdP+4dGuQcTNVl/gWXng1GLmfRxMmGVOLY3buGFmqS419ugE760t0u90Mskl1szon8/rX5vdXhPEa3bAWOVdKh9JcHN9Huo3SfFsc42p7SqCksxiy664aqhtTJ1WGPNKjTqLNVjag2G+BZKQttCFLw9vuR6UeYf3F6KSnoLXpFc7v1SLYn2jWr+NRIkqrOlTs3V/uz6ZROfSRAbNngp5EnjDT/+CSRwk=
